### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by Wujie-nju** [David0tt/DeepGTAV#12]
![image](https://user-images.githubusercontent.com/85567473/218456096-15799a59-86ae-43c0-9b65-908fb14c4785.png)
How can I install the GTAV?
Thank you very much

**Comment by David0tt** [comment]
You can install GTAV from the Epic Store or from Steam after buying it. DeepGTAV does work with these two versions. I believe it does not work with the Rockstar version, however i have not tested it.

**Comment by Air000** [comment]
> You can install GTAV from the Epic Store or from Steam after buying it. DeepGTAV does work with these two versions. I believe it does not work with the Rockstar version, however i have not tested it.

Right. After I finished all script installing steps, rockstar game launcher doesn't allow me to load GTAV anymore.

**Comment by Air000** [comment]
> You can install GTAV from the Epic Store or from Steam after buying it. DeepGTAV does work with these two versions. I believe it does not work with the Rockstar version, however i have not tested it.

But why it shows Rockstar install path in the example of README?

**Comment by David0tt** [comment]
> > You can install GTAV from the Epic Store or from Steam after buying it. DeepGTAV does work with these two versions. I believe it does not work with the Rockstar version, however i have not tested it.
> 
> Right. After I finished all script installing steps, rockstar game launcher doesn't allow me to load GTAV anymore.

This should not be the case. You could try to reinstall, and starting GTAV once before installing the scripts, to circumvent some correctness of installation checks. 

Other than that, maybe the version of GTAV has been updated, in this case you would have to recompile everything with a new version of ScripHookV
